// Sample product data
export const products = [
    {
      id: "nomad-pouch",
      name: "Nomad Pouch",
      description:
        "The Nomad Pouch is the perfect companion for your daily essentials. With a water-resistant exterior and compact design, it's ideal for keeping your small items organized whether you're traveling or just going about your day.",
      price: 5000,
      colorDescription: "White and Black",
      category: "hip-bags",
      colors: ["white", "black"],
      sizes: ["small", "medium"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Side",
        "/placeholder.svg?height=500&width=500&text=Open",
        "/placeholder.svg?height=500&width=500&text=Detail",
      ],
      rating: 4,
      date: "2023-01-15",
      collection: "bath-body",
      brand: "cosrx",
      skinType: ["oily", "combination"],
      skinConcern: ["daily-protection"],
    },
    {
      id: "zip-tote-basket",
      name: "Zip Tote Basket",
      description:
        "The Zip Tote Basket is the perfect midpoint between shopping tote and comfy backpack. With convertible straps, you can hand carry, shoulder sling, or backpack this convenient and spacious bag. The zip top and durable canvas construction keeps your goods protected for all-day use.",
      price: 14000,
      colorDescription: "Washed Black",
      category: "totes",
      colors: ["black", "white", "gray"],
      sizes: ["medium", "large"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Front",
        "/placeholder.svg?height=500&width=500&text=Side",
        "/placeholder.svg?height=500&width=500&text=Back",
      ],
      rating: 4,
      date: "2023-02-10",
      collection: "face",
      brand: "derma-factory",
      skinType: ["dry", "sensitive"],
      skinConcern: ["hyperpigmentation", "dehydrated-flaky"],
    },
    {
      id: "medium-stuff-sack",
      name: "Medium Stuff Sack",
      description:
        "The Medium Stuff Sack is perfect for organizing your travel essentials. Made from durable ripstop nylon, it keeps your clothes and accessories neatly packed and protected.",
      price: 3500,
      colorDescription: "Blue",
      category: "travel-bags",
      colors: ["blue", "black", "gray"],
      sizes: ["small", "medium", "large"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Open",
        "/placeholder.svg?height=500&width=500&text=Packed",
      ],
      rating: 5,
      date: "2023-03-05",
      collection: "spf",
      brand: "lizara",
      skinType: ["normal", "combination"],
      skinConcern: ["daily-protection", "sensitive"],
    },
    {
      id: "travel-case",
      name: "Travel Case",
      description:
        "Keep your travel essentials organized and secure with our Travel Case. Multiple compartments and a water-resistant design make it perfect for toiletries or small electronics.",
      price: 4500,
      colorDescription: "Black",
      category: "travel-bags",
      colors: ["black", "gray"],
      sizes: ["small", "medium"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Inside",
        "/placeholder.svg?height=500&width=500&text=Pockets",
      ],
      rating: 4,
      date: "2023-01-20",
      collection: "cleansers-toners",
      brand: "cosrx",
      skinType: ["oily", "combination"],
      skinConcern: ["acne-blemishes"],
    },
    {
      id: "zip-high-wall-tote",
      name: "Zip High Wall Tote",
      description:
        "The Zip High Wall Tote combines style and functionality with its spacious interior and secure zip closure. Perfect for work, travel, or everyday use.",
      price: 15000,
      colorDescription: "White and blue",
      category: "totes",
      colors: ["white", "blue"],
      sizes: ["large"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Side",
        "/placeholder.svg?height=500&width=500&text=Inside",
      ],
      rating: 5,
      date: "2023-04-15",
      collection: "hair-care",
      brand: "12-grabs",
      skinType: ["normal"],
      skinConcern: ["daily-protection"],
    },
    {
      id: "halfsize-tote",
      name: "Halfsize Tote",
      description:
        "The Halfsize Tote is a compact yet spacious bag perfect for daily essentials. Its minimalist design and premium materials make it a versatile addition to any outfit.",
      price: 21000,
      colorDescription: "Clay",
      category: "totes",
      colors: ["brown", "black", "white"],
      sizes: ["medium"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Front",
        "/placeholder.svg?height=500&width=500&text=Detail",
      ],
      rating: 4,
      date: "2023-02-28",
      collection: "bath-body",
      brand: "derma-factory",
      skinType: ["dry"],
      skinConcern: ["dehydrated-flaky", "sensitive"],
    },
    {
      id: "high-wall-tote",
      name: "High Wall Tote",
      description:
        "The High Wall Tote features extended sides for extra capacity while maintaining a sleek profile. Perfect for shopping, beach days, or as a stylish everyday carry.",
      price: 21000,
      colorDescription: "Black and orange",
      category: "totes",
      colors: ["black", "orange"],
      sizes: ["large"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Side",
        "/placeholder.svg?height=500&width=500&text=Top",
      ],
      rating: 5,
      date: "2023-05-10",
      collection: "face",
      brand: "lizara",
      skinType: ["combination"],
      skinConcern: ["hyperpigmentation"],
    },
    {
      id: "laptop-sleeve",
      name: "Laptop Sleeve",
      description:
        "Protect your laptop in style with our premium Laptop Sleeve. Featuring padded interior and water-resistant exterior to keep your device safe from bumps and weather.",
      price: 8000,
      colorDescription: "Gray",
      category: "laptop-sleeves",
      colors: ["gray", "black", "blue"],
      sizes: ["13-inch", "15-inch", "16-inch"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Open",
        "/placeholder.svg?height=500&width=500&text=Inside",
      ],
      rating: 4,
      date: "2023-03-20",
      collection: "spf",
      brand: "12-grabs",
      skinType: ["normal", "sensitive"],
      skinConcern: ["daily-protection"],
    },
    {
      id: "premium-cleanser",
      name: "Premium Cleanser",
      description:
        "Our Premium Cleanser gently removes impurities without stripping your skin's natural moisture. Perfect for daily use in your skincare routine.",
      price: 12000,
      colorDescription: "Clear",
      category: "skincare",
      colors: ["clear"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Usage",
        "/placeholder.svg?height=500&width=500&text=Ingredients",
      ],
      rating: 5,
      date: "2023-06-15",
      collection: "cleansers-toners",
      brand: "cosrx",
      skinType: ["all", "sensitive"],
      skinConcern: ["acne-blemishes", "sensitive"],
    },
    {
      id: "hydrating-serum",
      name: "Hydrating Serum",
      description:
        "This powerful serum delivers intense hydration and helps repair the skin barrier. Formulated with hyaluronic acid and ceramides for plump, healthy skin.",
      price: 25000,
      colorDescription: "Transparent",
      category: "skincare",
      colors: ["clear"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Dropper",
        "/placeholder.svg?height=500&width=500&text=Formula",
      ],
      rating: 4,
      date: "2023-07-10",
      collection: "face",
      brand: "derma-factory",
      skinType: ["dry", "normal"],
      skinConcern: ["dehydrated-flaky", "hyperpigmentation"],
    },
    {
      id: "sunscreen-spf50",
      name: "Sunscreen SPF50+",
      description:
        "Broad-spectrum protection against UVA and UVB rays. This lightweight, non-greasy formula absorbs quickly and doesn't leave a white cast.",
      price: 18000,
      colorDescription: "White",
      category: "skincare",
      colors: ["white"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Application",
        "/placeholder.svg?height=500&width=500&text=Texture",
      ],
      rating: 5,
      date: "2023-05-20",
      collection: "spf",
      brand: "lizara",
      skinType: ["all"],
      skinConcern: ["daily-protection", "hyperpigmentation"],
    },
    {
      id: "exfoliating-toner",
      name: "Exfoliating Toner",
      description:
        "Gentle chemical exfoliation with AHAs and BHAs to remove dead skin cells, unclog pores, and improve skin texture. Use 2-3 times weekly for best results.",
      price: 16000,
      colorDescription: "Clear",
      category: "skincare",
      colors: ["clear"],
      image: "/placeholder.svg?height=500&width=500",
      images: [
        "/placeholder.svg?height=500&width=500",
        "/placeholder.svg?height=500&width=500&text=Bottle",
        "/placeholder.svg?height=500&width=500&text=Liquid",
      ],
      rating: 4,
      date: "2023-04-05",
      collection: "cleansers-toners",
      brand: "cosrx",
      skinType: ["oily", "combination"],
      skinConcern: ["acne-blemishes", "hyperpigmentation"],
    },
  ]
  
  export const categories = [
    { id: "totes", name: "Totes" },
    { id: "backpacks", name: "Backpacks" },
    { id: "travel-bags", name: "Travel Bags" },
    { id: "hip-bags", name: "Hip Bags" },
    { id: "laptop-sleeves", name: "Laptop Sleeves" },
  ]
  
  export const colors = [
    { id: "white", name: "White" },
    { id: "black", name: "Black" },
    { id: "gray", name: "Gray" },
    { id: "blue", name: "Blue" },
    { id: "brown", name: "Brown" },
    { id: "orange", name: "Orange" },
  ]
  
  export const sizes = [
    { id: "small", name: "Small" },
    { id: "medium", name: "Medium" },
    { id: "large", name: "Large" },
    { id: "13-inch", name: "13 inch" },
    { id: "15-inch", name: "15 inch" },
    { id: "16-inch", name: "16 inch" },
  ]
  