import Navbar from "@/components/ui/landingPage/Navbar";
import type { Metadata } from "next";
import { Inter, Montserrat, Playfair, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const valky = localFont({
  src: "./fonts/Valky.woff2",
  variable: "--font-valky",
  weight: "100 900",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
});
const playfair = Playfair({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "700"],
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${valky.variable} ${roboto.variable} ${playfair.variable} ${inter.variable} bg-hokWhite`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
